# Linear Regression
This noteboooks is for linear regression model for stage one (find most important feature).

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from statsmodels.formula.api import ols, glm
from statsmodels.api import families
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [10]:
df = pd.read_csv("../../data/curated/domain_final2.csv")

In [11]:
df

,url,name,cost_text,type,school_title,school_distance,suburb_sold,suburb_avg_day,suburb_population,suburb_age,...,SA2_CODE21,avg_income,Median_tot_fam_inc_weekly,Tot_P_P,Median_age_persons,Median_rent_weekly,dist_nearest_busstop,dist_nearest_trainstation,dist_nearest_primary_school,dist_nearest_secondary_school
0,https://www.domain.com.au/1202-620-collins-str...,1202/620 Collins Street Melbourne VIC 3000,$500 per week,Apartment / Unit / Flat,University High School,2.4,596,147,"47,279",20 to 39,...,206041503,2035.430097,2248.0,9848.0,30.0,375.0,1000000,1000000,1000000,1000000
1,https://www.domain.com.au/1701-620-collins-str...,1701/620 Collins Street Melbourne VIC 3000,$650 per week,Apartment / Unit / Flat,University High School,2.4,596,147,"47,279",20 to 39,...,206041503,2035.430097,2248.0,9848.0,30.0,375.0,1000000,1000000,1000000,1000000
2,https://www.domain.com.au/5707b-639-little-lon...,5707B/639 Little Lonsdale Street Melbourne VIC...,$570,Apartment / Unit / Flat,University High School,1.9,387,120,"47,279",20 to 39,...,206041503,2035.430097,2248.0,9848.0,30.0,375.0,1000000,1000000,1000000,1000000
3,https://www.domain.com.au/1003-225-elizabeth-s...,1003/225 Elizabeth Street Melbourne VIC 3000,$575.00 per week,Apartment / Unit / Flat,Carlton Gardens Primary School,1.4,596,147,"47,279",20 to 39,...,206041503,2035.430097,2248.0,9848.0,30.0,375.0,1000000,1000000,1000000,1000000
4,https://www.domain.com.au/1202-31-spring-stree...,1202/31 Spring Street Melbourne VIC 3000,$570.00,Apartment / Unit / Flat,Carlton Gardens Primary School,1.4,596,147,"47,279",20 to 39,...,206041503,2035.430097,2248.0,9848.0,30.0,375.0,1000000,1000000,1000000,1000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12762,https://www.domain.com.au/6-bruce-street-inver...,6 Bruce Street Inverloch VIC 3996,$400,House,Inverloch Primary School,0.2,81,49,"5,431",60+,...,205031087,1574.763667,1466.0,9446.0,54.0,250.0,1000000,1000000,1000000,1000000
12763,https://www.domain.com.au/14-inverloch-parade-...,14 Inverloch Parade Inverloch VIC 3996,$420 wk,House,Inverloch Primary School,0.7,25,56,"5,431",60+,...,205031087,1574.763667,1466.0,9446.0,54.0,250.0,1000000,1000000,1000000,1000000
12764,https://www.domain.com.au/inverloch-vic-3996-1...,Inverloch VIC 3996,$475 wk,House,Inverloch Primary School,0.1,81,49,"5,431",60+,...,205031087,1574.763667,1466.0,9446.0,54.0,250.0,1000000,1000000,1000000,1000000
12765,https://www.domain.com.au/25a-veronica-street-...,25A Veronica Street Inverloch VIC 3996,400 per week,House,Inverloch Primary School,2.1,81,49,"5,431",60+,...,205031087,1574.763667,1466.0,9446.0,54.0,250.0,1000000,1000000,1000000,1000000
12766,https://www.domain.com.au/28-beachcomber-drive...,28 Beachcomber Drive Inverloch VIC 3996,$550 wk,House,Inverloch Primary School,2.5,66,78,"5,431",60+,...,205031087,1574.763667,1466.0,9446.0,54.0,250.0,1000000,1000000,1000000,1000000

In [9]:
# aggregate data by psotcode
df_postcode = df\
                .groupby('postcode') \
                .agg(
                    {
                        'cost':'mean',
                        'Median_rent_weekly':'mean',
                        'school_distance':'mean',
                        'dist_nearest_busstop':'mean',
                        'dist_nearest_trainstation':'mean',
                        'dist_nearest_primary_school':'mean',
                        'dist_nearest_secondary_school':'mean',
                        'Beds':'mean',
                        'Bath':'mean',
                        'Parking':'mean',
                        'avg_income':'mean',
                        'Tot_P_P':'mean',
                        'Median_age_persons': 'mean',
                        'suburb_sold': 'mean',
                        'suburb_avg_day': 'mean',
                        'suburb_population': 'mean',
                        'suburb_owner': 'mean',
                        'suburb_renter':'mean',
                        'suburb_family':'mean',
                        'suburb_single':'mean',
                    }
                ) 
df_postcode.head()

TypeError: Could not convert 30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30%30% to numeric

In [ ]:
# check linear relationship between features and respond varible
sns.lmplot(x="suburb_population", y="cost", data=df_postcode)

In [ ]:
sns.lmplot(x="dist_nearest_busstop", y="cost", data=df_postcode)

In [ ]:
sns.lmplot(x="avg_income", y="cost", data=df_postcode)

In [ ]:
# check correlation of features

CORR_COLS = [
    'cost','school_distance','suburb_population','suburb_renter',
    'suburb_single','dist_nearest_secondary_school', 'dist_nearest_busstop',
    'dist_nearest_trainstation' , 'dist_nearest_primary_school',
    'avg_income','Tot_P_P','Median_age_persons','Beds','Bath','Parking'
]


fig,ax = plt.subplots(figsize=(17,5)) 
sns.heatmap(df_postcode[CORR_COLS].corr(), cmap = plt.cm.RdYlBu_r,annot=True, ax = ax)

plt.title('Pearson Correlation Metric')
#plt.savefig('../plots/corr.png')

In [ ]:
CORR_COLS = [
    'cost','school_distance','suburb_population','suburb_renter',
    'dist_nearest_secondary_school','dist_nearest_trainstation' , 
    'avg_income','Tot_P_P','Median_age_persons','Beds','Bath','Parking'
]


fig,ax = plt.subplots(figsize=(20,5)) 
sns.heatmap(df_postcode[CORR_COLS].corr(), cmap = plt.cm.RdYlBu_r,annot=True, ax = ax)

plt.title('Pearson Correlation Metric')
#plt.savefig('../plots/corr.png')

In [ ]:
x = df_postcode[['cost','suburb_population','suburb_renter','suburb_family',
    'dist_nearest_secondary_school','dist_nearest_trainstation' , 
    'avg_income','Tot_P_P','Median_age_persons','Beds','Bath','Parking']].values
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df1 = pd.DataFrame(x_scaled, columns= ['cost','suburb_population','suburb_renter','suburb_family',
    'dist_nearest_secondary_school','dist_nearest_trainstation' , 
    'avg_income','Tot_P_P','Median_age_persons','Beds','Bath','Parking'] )

In [ ]:
df1

In [ ]:
# training model
fit = ols(
    formula="cost ~ suburb_population + suburb_renter + suburb_family + dist_nearest_secondary_school + avg_income \
    + Tot_P_P + dist_nearest_trainstation + Median_age_persons + Bath + Parking",
    data=df1
).fit()
print(fit.summary())

In [ ]:
fit = ols(
    formula="cost ~ avg_income + Tot_P_P + dist_nearest_trainstation + Median_age_persons + Bath + Parking",
    data=df1
).fit()
print(fit.summary())