In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [2]:
df = pd.read_csv("./2016_data.csv")

In [3]:
df_21 = pd.read_csv("./2021_data.csv")

In [4]:
bed_16 = pd.read_csv("./df_bed_2016(1).csv")
bed_21 = pd.read_csv("./df_bed_2021(1).csv")

bed_16 = bed_16.rename(columns={'SA2_2016': 'SA2_CODE16'})
bed_21 = bed_21.rename(columns={'SA2_2021': 'SA2_CODE16'})

In [6]:
bed_21

     SA2_CODE16  avg_beds_2021
0     201011001        3.58401
1     201011002        3.01184
2     201011005        3.45792
3     201011006        3.47034
4     201011007        3.62337
..          ...            ...
519   217041478        3.25182
520   217041479        3.15654
521   217041480        2.94790
522   297979799            NaN
523   299999499            NaN

[524 rows x 2 columns]

In [7]:
df

,SA2_CODE16,avg_income,Median_tot_fam_inc_weekly,Tot_P_P,Median_age_persons,Median_rent_weekly
0,201011001,1862.008106,1833,11654,34,310
1,201011002,1794.138669,1867,12046,42,260
2,201011003,1540.676654,1574,23083,39,250
3,201011004,1236.168969,1242,24231,36,240
4,201011005,1937.960572,1921,7153,38,300
...,...,...,...,...,...,...
459,217041478,1536.300891,1470,9432,44,223
460,217041479,1520.163543,1510,21097,39,250
461,217041480,1485.872396,1498,12921,43,250
462,297979799,NaN,0,29,49,0
463,299999499,NaN,0,7565,34,0

In [8]:
df_21 = df_21.rename(columns={'SA2_CODE21': 'SA2_CODE16','Median_rent_weekly':'Median_rent_weekly_21'})

In [9]:
# df_new = pd.merge(df, df_21[['SA2_CODE16','Median_rent_weekly_21']], how = 'left', on='SA2_CODE16')
df = pd.merge(df, bed_16,  on='SA2_CODE16')
df_new = pd.merge(df, df_21[['SA2_CODE16','Median_rent_weekly_21']],  on='SA2_CODE16')

In [10]:
df_new.Median_rent_weekly_21.isnull().sum()

0

In [11]:
df_new['label'] = (df_new['Median_rent_weekly_21']-df_new['Median_rent_weekly'])/(df_new['Median_rent_weekly']+1e-5)

In [12]:
df_new

,SA2_CODE16,avg_income,Median_tot_fam_inc_weekly,Tot_P_P,Median_age_persons,Median_rent_weekly,avg_beds_2016,Median_rent_weekly_21,label
0,201011001,1862.008106,1833,11654,34,310,3.48760,370,0.193548
1,201011002,1794.138669,1867,12046,42,260,2.97632,313,0.203846
2,201011005,1937.960572,1921,7153,38,300,3.41499,330,0.100000
3,201011006,1502.571300,1465,7082,36,260,3.32975,360,0.384615
4,201011007,1815.179581,1745,3932,41,236,3.47918,350,0.483051
...,...,...,...,...,...,...,...,...,...
405,217041478,1536.300891,1470,9432,44,223,3.20240,280,0.255605
406,217041479,1520.163543,1510,21097,39,250,3.11719,300,0.200000
407,217041480,1485.872396,1498,12921,43,250,2.91604,287,0.148000
408,297979799,NaN,0,29,49,0,NaN,0,0.000000
409,299999499,NaN,0,7565,34,0,NaN,0,0.000000

In [13]:
df_train = df_new[(df_new.Median_rent_weekly != 0) & (df_new.avg_income.notna())]
df_train = df_train[df_train.Tot_P_P > 1000]

In [14]:
df_train

,SA2_CODE16,avg_income,Median_tot_fam_inc_weekly,Tot_P_P,Median_age_persons,Median_rent_weekly,avg_beds_2016,Median_rent_weekly_21,label
0,201011001,1862.008106,1833,11654,34,310,3.48760,370,0.193548
1,201011002,1794.138669,1867,12046,42,260,2.97632,313,0.203846
2,201011005,1937.960572,1921,7153,38,300,3.41499,330,0.100000
3,201011006,1502.571300,1465,7082,36,260,3.32975,360,0.384615
4,201011007,1815.179581,1745,3932,41,236,3.47918,350,0.483051
...,...,...,...,...,...,...,...,...,...
403,217031476,1228.678722,1205,3429,52,245,2.90776,285,0.163265
404,217041477,1539.953835,1482,6648,42,150,3.29440,200,0.333333
405,217041478,1536.300891,1470,9432,44,223,3.20240,280,0.255605
406,217041479,1520.163543,1510,21097,39,250,3.11719,300,0.200000
407,217041480,1485.872396,1498,12921,43,250,2.91604,287,0.148000

In [15]:
# df_train['Median_tot_fam_inc_weekly_avg_income_div'] = (df_train['Median_tot_fam_inc_weekly'] - df_train['avg_income']) / df_train['avg_income']
df_train['Median_age_persons_Tot_P_P_div'] = (df_train['Median_age_persons'] - df_train['Tot_P_P']) / df_train['Tot_P_P']

In [16]:
df_train.isnull().any()

SA2_CODE16                        False
avg_income                        False
Median_tot_fam_inc_weekly         False
Tot_P_P                           False
Median_age_persons                False
Median_rent_weekly                False
avg_beds_2016                     False
Median_rent_weekly_21             False
label                             False
Median_age_persons_Tot_P_P_div    False
dtype: bool

In [17]:
df_train.corr()

,SA2_CODE16,avg_income,Median_tot_fam_inc_weekly,Tot_P_P,Median_age_persons,Median_rent_weekly,avg_beds_2016,Median_rent_weekly_21,label,Median_age_persons_Tot_P_P_div
SA2_CODE16,1.000000,-0.062573,-0.115391,0.101324,-0.107661,-0.060528,0.168866,-0.074997,0.013276,-0.042827
avg_income,-0.062573,1.000000,0.964909,0.222674,-0.358891,0.818510,0.089118,0.824265,-0.411898,-0.324905
Median_tot_fam_inc_weekly,-0.115391,0.964909,1.000000,0.206118,-0.298304,0.764315,-0.088231,0.767976,-0.384358,-0.291505
Tot_P_P,0.101324,0.222674,0.206118,1.000000,-0.351370,0.437130,-0.064764,0.407135,-0.412805,-0.821190
Median_age_persons,-0.107661,-0.358891,-0.298304,-0.351370,1.000000,-0.503832,0.125987,-0.421669,0.537307,0.573890
Median_rent_weekly,-0.060528,0.818510,0.764315,0.437130,-0.503832,1.000000,-0.015085,0.973131,-0.680127,-0.559171
avg_beds_2016,0.168866,0.089118,-0.088231,-0.064764,0.125987,-0.015085,1.000000,0.060201,0.162267,0.084273
Median_rent_weekly_21,-0.074997,0.824265,0.767976,0.407135,-0.421669,0.973131,0.060201,1.000000,-0.520447,-0.511762
label,0.013276,-0.411898,-0.384358,-0.412805,0.537307,-0.680127,0.162267,-0.520447,1.000000,0.566007
Median_age_persons_Tot_P_P_div,-0.042827,-0.324905,-0.291505,-0.821190,0.573890,-0.559171,0.084273,-0.511762,0.566007,1.000000

In [18]:
df_train.columns

Index(['SA2_CODE16', 'avg_income', 'Median_tot_fam_inc_weekly', 'Tot_P_P',
       'Median_age_persons', 'Median_rent_weekly', 'avg_beds_2016',
       'Median_rent_weekly_21', 'label', 'Median_age_persons_Tot_P_P_div'],
      dtype='object')

In [19]:
#Test Set
df_ceshi = df_21[['SA2_CODE16', 'avg_income', 'Tot_P_P','Median_age_persons']]
df_ceshi = pd.merge(df_ceshi, bed_21,  on='SA2_CODE16')

In [20]:
# df_ceshi['Median_age_persons_Tot_P_P_div'] = (df_ceshi['Median_age_persons'] - df_ceshi['Tot_P_P']) / df_ceshi['Tot_P_P']

In [23]:
df_ceshi = df_ceshi[(df_ceshi.avg_income.notna())]
df_ceshi = df_ceshi[df_ceshi.Tot_P_P > 1000]

In [24]:
df_ceshi.isnull().any()

SA2_CODE16            False
avg_income            False
Tot_P_P               False
Median_age_persons    False
avg_beds_2021         False
dtype: bool

In [25]:
df_ceshi

     SA2_CODE16   avg_income  Tot_P_P  Median_age_persons  avg_beds_2021
0     201011001  2269.734428    16835                  34        3.58401
1     201011002  2130.397616    12131                  45        3.01184
2     201011005  2313.068493     7261                  42        3.45792
3     201011006  1857.987190    10661                  33        3.47034
4     201011007  2311.064133     4230                  41        3.62337
..          ...          ...      ...                 ...            ...
517   217031476  1628.483882     4008                  52        2.98404
518   217041477  1937.815824     7018                  42        3.31098
519   217041478  1905.366053    10014                  46        3.25182
520   217041479  1850.573197    22405                  40        3.15654
521   217041480  1823.943042    13337                  44        2.94790

[509 rows x 5 columns]

In [26]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [27]:
std_scaler = MinMaxScaler()
df_train_scaled = std_scaler.fit_transform(df_train[[f for f in df_train.columns if f not in 
                                            ['Median_rent_weekly','Median_rent_weekly_21',
                                             'Median_age_persons_Tot_P_P_div',
                                            'Median_tot_fam_inc_weekly', 'label']]])

In [28]:
df_ceshi_scaled = std_scaler.fit_transform(df_ceshi[[f for f in df_ceshi.columns if f not in 
                                            ['Median_rent_weekly','Median_rent_weekly_21',
                                             'Median_age_persons_Tot_P_P_div',
                                            'Median_tot_fam_inc_weekly', 'label']]])

In [29]:
y_scaler = MinMaxScaler()
y_train_scaled = y_scaler.fit_transform(df_train[['label']])

In [30]:
df_train_scaled = pd.DataFrame(df_train_scaled)

In [31]:
df_train_scaled

                0         1         2         3         4
0    0.000000e+00  0.442336  0.427161  0.285714  0.769793
1    6.238117e-08  0.406492  0.445594  0.514286  0.548764
2    2.495247e-07  0.482448  0.215508  0.400000  0.738403
3    3.119058e-07  0.252509  0.212170  0.342857  0.701554
4    3.742870e-07  0.417604  0.064046  0.485714  0.766153
..            ...       ...       ...       ...       ...
391  9.993759e-01  0.107861  0.040393  0.800000  0.519125
392  9.999998e-01  0.272252  0.191761  0.514286  0.686272
393  9.999999e-01  0.270323  0.322675  0.571429  0.646500
394  9.999999e-01  0.261800  0.871203  0.428571  0.609663
395  1.000000e+00  0.243690  0.486739  0.542857  0.522705

[396 rows x 5 columns]

In [198]:
X_train, X_test, y_train, y_test = train_test_split(df_train_scaled, y_train_scaled, 
                                                    test_size = 0.2, random_state = 23)

In [199]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(316, 5)
(316, 1)
(80, 5)
(80, 1)

In [200]:
from sklearn import linear_model

In [201]:
lr = linear_model.LinearRegression()
lr.fit(X_train,y_train)

y_pred = lr.predict(X_test)

In [202]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

print('The MSE is:', mean_squared_error(y_test, y_pred))

print('The R2 is:', r2_score(y_test, y_pred))

print('The MAE is:', mean_absolute_error(y_test, y_pred))

The MSE is: 0.006255038523831538
The R2 is: 0.46615876342906526
The MAE is: 0.04833936527887263

In [203]:
from sklearn.neural_network import MLPRegressor

In [204]:
clf = MLPRegressor(solver='lbfgs', alpha=1e-3, hidden_layer_sizes=(80,7), activation='relu', random_state=20)

clf.fit(X_train,y_train)

y_pred_2 = clf.predict(X_test)

D:\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1599: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

In [205]:
print('The R2 is:', r2_score(y_train, clf.predict(X_train)))

The R2 is: 0.6578309964607314

In [206]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

print('The MSE is:', mean_squared_error(y_test, y_pred_2))

print('The R2 is:', r2_score(y_test, y_pred_2))

print('The MAE is:', mean_absolute_error(y_test, y_pred_2))

The MSE is: 0.006339482826955961
The R2 is: 0.4589517972322049
The MAE is: 0.04530666148050463

In [207]:
clf.predict(X_test)

array([0.30959294, 0.32521209, 0.28685705, 0.2689224 , 0.3247142 ,
       0.32318272, 0.29351947, 0.26056933, 0.32540189, 0.54132993,
       0.18359377, 0.36161498, 0.27038194, 0.31657693, 0.31481116,
       0.38457512, 0.24611809, 0.25233141, 0.28313546, 0.28722532,
       0.32540664, 0.39503391, 0.35341767, 0.36793937, 0.34078948,
       0.40621666, 0.25752959, 0.30117871, 0.70533413, 0.44980052,
       0.2600838 , 0.32122664, 0.24634147, 0.26631056, 0.21100292,
       0.31525359, 0.29150919, 0.26215347, 0.40901641, 0.16042308,
       0.45876555, 0.2033943 , 0.31202952, 0.13872118, 0.30337426,
       0.4695462 , 0.31290455, 0.20687615, 0.29805546, 0.27572477,
       0.31084008, 0.43000811, 0.29099026, 0.3199542 , 0.40155813,
       0.39144793, 0.29514434, 0.30303407, 0.45028366, 0.2759555 ,
       0.35487859, 0.44073118, 0.48455605, 0.34964844, 0.26290797,
       0.23613849, 0.33104919, 0.25912046, 0.27176633, 0.22290437,
       0.34789084, 0.38588617, 0.37817568, 0.44188582, 0.29843252,
       0.28884809, 0.41650157, 0.35507483, 0.27313272, 0.1879458 ])

In [208]:
cengindex = 0
for wi in clf.coefs_:
    cengindex += 1  # 第几层神经网络
    print('第%d层网络层:' % cengindex)
    print('权重矩阵维度:',wi.shape)
    print('系数矩阵：\n',wi)

第1层网络层:
权重矩阵维度: (5, 80)
系数矩阵：
 [[ 4.44558582e-02  3.32196797e-01  1.44313525e-01  3.81270398e-01
  -5.27354231e-01  1.55879353e-01 -4.95374949e-02 -2.17635248e-02
   7.96755263e-02 -1.54431267e-01 -1.62962064e-01  2.30173269e-01
   6.72413128e-02  5.37240431e-01  1.20156390e-01 -2.33720625e-01
   6.94896554e-03  1.16955010e-01 -1.22777844e-01 -1.23683309e-01
   1.70277776e-01  2.34597380e-01  8.07252350e-03 -4.44600922e-01
   2.57153507e-01  5.78663801e-02  8.01485936e-02  3.75266468e-01
  -5.00799168e-02  1.09372662e-02  1.27920231e-01  7.23167742e-02
  -2.75787764e-02 -4.69304857e-01  1.87090722e-01  1.37198355e-01
  -9.37584476e-02  5.09212665e-02 -1.19232812e-01  1.23732015e-01
   6.39887346e-02  2.89794329e-02 -9.15139914e-02 -5.21872799e-02
  -1.21139373e-01  2.64703206e-02 -4.49215261e-03 -1.60541777e-01
   1.60168780e-01 -1.73326474e-01  3.08758669e-01 -4.60830332e-02
   1.41209941e-01  1.09240174e-01 -3.37176171e-02  2.88157324e-01
   1.88158161e-01  6.99963381e-02 -4.71745033e-02  1.83043961e-02
  -8.43290742e-03 -2.84490551e-01  6.14168844e-02  6.38317881e-02
   1.60002973e-01 -2.04751008e-02 -6.06297362e-02  2.86722064e-01
   8.20975428e-02 -2.60849905e-01  8.04495600e-03  4.40702826e-01
   1.41773754e-01  3.47844885e-01  1.04258741e-01  1.19403049e-01
   1.37899198e-02 -1.01380039e-01 -1.24582143e-01 -1.07832518e-01]
 [-2.27923174e-01  1.08386146e-01 -1.18486860e-01 -5.11462756e-01
  -3.90030718e-01 -1.90757251e-01  2.18757372e-01 -1.70446352e-01
  -1.97934838e-01 -1.93195963e-01  7.71026362e-02  1.13337892e-01
  -2.12415937e-01  5.55359996e-02  1.65161318e-01  7.61298226e-03
   2.70811280e-01  3.26602555e-02  8.61378819e-02 -3.90041277e-02
   1.01811810e-01  3.65213250e-03 -3.35086255e-01  9.23571523e-02
  -1.53606350e-01  2.30110073e-01 -4.26987289e-02 -8.55093046e-02
  -6.82395688e-02  4.62630186e-02  1.69360432e-01 -1.48703995e-01
   1.44798808e-01 -2.12588488e-01  2.84319588e-01 -2.59750697e-01
   1.97684905e-01 -5.18503908e-02 -2.09521080e-01  1.61209829e-01
   2.50500584e-01 -2.47376331e-01 -1.32375970e-01  5.67152614e-02
   1.58780469e-01  2.01817601e-01  1.63624690e-01  2.64937321e-01
   9.71810883e-03 -2.97230891e-02  6.86034147e-02  1.14324605e-01
   9.31290395e-02 -5.19861694e-02  4.75668565e-01 -5.45445010e-02
  -3.07950465e-01  5.86379865e-02  2.15863430e-01 -2.01632728e-01
  -2.28338813e-01  1.75992552e-01  1.83428936e-01  1.95617314e-01
   1.68322532e-01 -1.35815815e-01 -1.98996671e-01  5.62081191e-02
  -3.02219891e-02 -3.44464132e-02  8.91270510e-02  2.64357385e-01
  -1.18973857e-01  2.68491842e-01  2.15844247e-01  3.38002761e-01
   9.14848749e-02  3.08563750e-01 -2.21088487e-01  1.39329142e-02]
 [-4.55656530e-02 -1.09966046e-01  2.60442472e-02  2.12368281e-03
   3.33877898e-01  6.09583479e-02  1.51252394e-01  1.87411293e-01
   1.83798937e-01  1.42616999e-01 -1.98322191e-01 -2.19154095e-01
   2.56547524e-01 -7.70091436e-01 -8.36471765e-02  7.00467581e-02
   7.01922296e-02  1.11305293e-01 -4.13096957e-02  2.27656764e-01
  -1.43548647e-01 -4.10786948e-02 -1.16084868e+00  5.07731758e-01
   2.12653878e-02  1.04680244e-01 -1.64802837e-01  4.47625384e-02
   6.08309240e-03  2.07040684e-01  2.16321834e-01  3.68468480e-02
   6.84278078e-02  3.54362508e-01 -1.40546605e-01  2.09614293e-01
   2.51926152e-01  4.12677091e-02  6.57637053e-02  3.01765918e-01
  -5.17306922e-02  1.78552221e-03 -1.00624870e-02  2.43916952e-01
  -2.53384927e-01 -2.28064545e-01 -4.20547122e-01  4.53164038e-01
  -1.12268294e-01  5.71488311e-02  8.32654201e-02  1.44843718e-01
   1.61066026e-01  2.13242049e-01 -2.92991358e-01  4.65193077e-01
   1.35363915e-01 -1.57584957e-01  7.14743676e-01 -1.15939413e-01
  -1.76509980e-02 -1.52104170e-02  2.60566640e-01  3.63973542e-01
   5.71956982e-01  6.73936911e-02 -2.18614662e-01  9.17307180e-02
  -2.17919543e-01  3.31772591e-01  2.60094310e-01 -1.95378583e-01
   7.53433886e-02  6.87636789e-01  4.24125446e-01  1.09807037e-01
  -1.24614642e-01 -6.35845376e-01  5.53937013e-02  1.96560227e-01]
 [-3.10170897e-02 -1.22914003e-01 -3.54441728e-02  6.27591564e-02
   5.98786390e-02 -2.68991881e-01 -9.88877262e-02  1.10105663e-02
  -2.24490140e-01 -1.45518176e-01  1.21154164e-01 -1.44960423e-01
  -3.17049800e-01 -4.70922403e-01  5.42659882e-03 -7.00758593e-02
   2.24800771e-01 -1.75556473e-01  2.44817299e-01 -1.08034753e-02
   2.27132908e-01  4.50879426e-02 -2.53150079e-01 -1.90286194e-01
   4.63284326e-01  2.63344967e-01  8.15385935e-02 -5.37039404e-02
  -4.03565432e-02  4.65707020e-02 -8.46187081e-02 -4.57888771e-02
   5.36970688e-02  8.72073210e-02  4.35467685e-02 -8.45058776e-03
   9.70369440e-02  1.81479078e-02  1.54745213e-01  1.27920298e-01
  -1.47855965e-01 -4.75181745e-03 -1.55203201e-01 -2.08751536e-01
  -9.11193118e-02  2.87191363e-02 -1.40753428e-01  1.86820296e-01
   1.13117770e-02 -1.86405071e-01  8.67984133e-02 -1.44857265e-01
  -1.36442206e-01 -5.92010670e-02 -4.12947904e-02 -1.34976839e-01
  -1.06500382e-01  2.58757851e-01  4.90797762e-01  1.00648020e-01
   2.09399049e-01  8.15030480e-02  5.94384007e-02 -9.40570298e-02
  -3.89218065e-01 -9.54876156e-02  2.42383359e-01  1.13777794e-01
   1.97437383e-01  3.44288509e-02  9.74602547e-04 -2.75290371e-01
  -2.95622537e-01 -3.37155817e-01 -1.56131122e-01 -1.69589363e-01
   2.31858977e-01  1.81248097e-01  2.88846617e-01  2.84291958e-02]
 [-2.36007704e-01  1.08382315e-01 -2.43027137e-01 -3.58709946e-01
   1.31634671e-01  1.77833455e-02  9.91973651e-02 -3.98702609e-02
   1.01610243e-01  9.61503745e-02 -1.20101119e-02 -1.42492484e-02
  -2.29781117e-01 -3.30397190e-01  1.17584247e-01 -2.26629960e-01
   1.68349368e-02 -1.47305630e-01 -2.30449375e-01  8.16580727e-02
  -1.69474149e-01 -1.33259380e-02 -2.83818599e-02  1.74568618e-01
   2.44915806e-01  5.24427415e-02  1.31323185e-01 -9.23273908e-02
  -2.27856980e-01  1.78942962e-01  2.85536571e-01  1.49734264e-02
   5.74093315e-02 -1.05068348e-01  1.44957673e-01 -3.89090653e-01
  -2.49688099e-01  2.30616211e-01  1.90189930e-01 -7.91214816e-02
  -1.75102786e-01 -6.26525085e-02 -1.88757245e-01  2.31821590e-01
   2.23586979e-01 -2.31232658e-01  2.61196244e-01  9.23210365e-02
   2.30779752e-01  8.12101850e-02 -1.97923074e-01 -4.67464358e-02
   2.35059922e-01 -1.52731345e-01 -3.71584334e-01 -1.44062897e-01
  -8.23911256e-03 -2.56706582e-01  6.73210741e-02 -9.79043064e-02
  -1.79007906e-01 -3.41498755e-01  3.05598887e-02 -1.11909108e-01
   1.72870918e-01  6.47075791e-02 -7.82208492e-02 -1.61043092e-01
   3.05633075e-01  3.25225862e-01 -2.10525841e-01 -2.05901369e-01
  -1.31313485e-01 -2.87486256e-01 -2.60125830e-01  2.44253125e-01
  -1.52606049e-01  3.31053130e-01 -1.99286854e-01  8.49232296e-02]]
第2层网络层:
权重矩阵维度: (80, 7)
系数矩阵：
 [[-1.40128362e-01 -2.36311334e-01 -1.07892931e-01 -1.89871875e-01
  -1.09581073e-01  4.33991459e-02 -2.35222691e-01]
 [-2.35730072e-01  2.37396642e-01  1.32068285e-02 -1.16272966e-01
  -7.10883769e-02 -2.73404659e-02  1.45481018e-01]
 [-1.87763204e-01  2.50050523e-01  2.04725947e-01  1.71482978e-01
  -2.39219497e-01 -2.06374262e-01 -1.83574507e-01]
 [ 3.86239832e-02 -1.90696722e-01  3.57563439e-02  9.47583471e-02
   1.20265948e-01 -3.11453486e-01  3.65389643e-01]
 [ 1.08176134e-01 -3.15802921e-01 -1.12061794e-01 -7.22377519e-02
  -3.51159160e-02 -1.10953297e-02 -4.72961314e-01]
 [-2.20641245e-01 -5.20052507e-02 -6.83254716e-03 -1.19754488e-01
  -2.42001727e-01  1.54630339e-01 -3.08625467e-01]
 [ 6.85591881e-02  1.81355635e-01  1.17460735e-01  2.42849989e-02
  -1.04413139e-02  2.37902193e-01  2.07064403e-01]
 [-2.19089353e-01 -8.61255753e-02 -1.01890730e-01  8.54309585e-02
   3.28869725e-02 -1.68258276e-01  1.03520298e-01]
 [-1.78358123e-01 -1.63460834e-01 -1.89981209e-01  1.36211685e-01
   8.90759300e-02 -2.15336401e-02 -2.46619649e-01]
 [ 8.87973977e-02  2.01043624e-01  2.04106869e-01  1.39382103e-01
   7.73599730e-02 -2.42306843e-01  1.63257479e-01]
 [ 1.56844912e-01 -6.90207987e-02  1.19211491e-01  2.04585812e-01
  -1.05948507e-01 -2.33184451e-01  1.39182087e-01]
 [-1.18466275e-01  8.68460343e-02  3.76986838e-02  3.45342881e-02
  -1.23164259e-01 -1.93372540e-03  1.90321779e-04]
 [-2.30361056e-01  1.45778194e-01  2.33326408e-01 -2.16928523e-01
  -1.34731977e-01 -1.30597185e-01  2.30189151e-01]
 [-1.58586030e-01 -4.48187485e-01 -9.66156559e-02  8.18943630e-02
  -3.53157774e-02  1.07577421e-02 -3.81724896e-01]
 [ 2.32200387e-01  7.44283099e-02  8.50952766e-02  5.45830969e-02
  -1.79612430e-01  2.17093605e-01  4.00518687e-03]
 [-2.23544844e-01  1.64296649e-02 -1.26243697e-01  1.37723251e-01
  -7.45779911e-02 -1.68135098e-01  2.33026821e-01]
 [-1.81757029e-01  7.61709873e-02  4.78723615e-02  1.59898913e-01
  -4.54998466e-02 -2.45100456e-01 -5.19115531e-02]
 [-1.03725226e-01 -1.81022030e-01  1.35340086e-01  3.45002977e-02
   2.48966431e-01 -2.37684095e-01 -9.51538858e-02]
 [ 2.16616049e-01 -2.41680663e-01  3.86485338e-02 -3.00287812e-02
  -1.75469044e-01  4.96248493e-02  2.13496322e-01]
 [ 2.62715330e-02 -1.45820673e-01 -1.09038215e-01  1.37618130e-01
   1.95297897e-01  1.47501004e-01  2.17454226e-01]
 [-1.06638615e-01 -1.66173900e-01 -1.30634878e-01 -2.24775665e-01
  -1.78585651e-01 -2.02099093e-03 -4.31207495e-02]
 [ 1.49604651e-01 -2.64495492e-03 -2.56410977e-01  3.29119485e-02
  -6.92477167e-02  1.67170924e-01  4.94001132e-03]
 [ 2.47534070e-01 -2.88571152e-02 -2.36778073e-01  2.39053885e-02
  -1.24068152e-01  4.01447045e-01 -1.06951492e+00]
 [-7.98322674e-02 -4.32434171e-02  5.84223447e-02 -1.96997016e-01
  -1.06133504e-01  1.44329936e-01 -3.79937237e-01]
 [-1.32975042e-01  2.91002578e-02  1.81458448e-01 -2.42661361e-01
   9.44440772e-02 -1.16382949e-01  3.69218584e-01]
 [ 1.84372392e-02 -9.40053871e-02 -9.83344365e-02 -2.36639400e-01
  -1.57021477e-01  7.75862508e-02  1.76603531e-01]
 [-2.49944576e-01 -8.31017612e-02  8.47395618e-02  2.22079316e-01
  -2.17149894e-01  2.69108056e-01 -5.85065549e-02]
 [-7.94263055e-02 -5.57643171e-02  9.96872948e-02  6.51256898e-02
   1.31082082e-01 -8.71677338e-02 -3.86198293e-01]
 [-4.23855149e-02 -4.08393382e-02  8.70159308e-02 -6.25987923e-02
   2.33621137e-01 -9.68258765e-02 -2.15641607e-01]
 [ 9.35633900e-02  1.52111654e-01 -2.01030501e-01  8.61699146e-02
  -2.33131268e-01  2.03644725e-01  1.63211847e-01]
 [ 2.05508523e-01  3.58485176e-01 -2.49266983e-01 -1.91590733e-01
  -2.17069934e-01  2.09697448e-01  5.67305301e-02]
 [ 2.21979775e-01  8.62741860e-02 -1.48634722e-01 -2.03690900e-01
   6.28500983e-02  1.64660944e-01 -7.11851346e-02]
 [-2.05725010e-01 -5.57767505e-02 -2.31188145e-01 -2.60353981e-01
   2.00989087e-01  9.01295069e-02  1.91212927e-01]
 [ 6.53764071e-02 -1.12109917e-01  1.59369488e-01 -6.44586312e-02
  -2.19397473e-01 -3.10164365e-01  4.16718898e-01]
 [-1.80151760e-01  8.14404165e-02 -2.99616202e-01  2.30679606e-02
   1.14746699e-01  2.93720432e-01  1.46082647e-02]
 [-7.84921787e-02 -2.75904765e-02 -6.75930898e-02 -8.41986561e-02
   1.14548657e-01 -1.81256181e-01  1.01377663e-01]
 [-4.51232609e-02  6.79437736e-03  9.99547968e-03 -2.19128829e-01
   2.09391825e-02 -1.03391824e-01  2.69964026e-01]
 [ 1.35381041e-02 -4.65589795e-03 -1.81187257e-01 -6.22650604e-02
  -1.37269617e-01 -2.03627425e-02  3.79975947e-03]
 [ 1.11190913e-01 -2.15399140e-01  1.84611089e-01 -5.67839428e-02
   8.49122177e-03  2.23862972e-01  1.16509089e-01]
 [ 4.01605784e-02  1.71398114e-02  1.06568781e-01  1.26745342e-01
  -7.43844609e-02  7.27269451e-02  2.63950986e-01]
 [ 7.99358541e-02 -1.18710182e-01 -1.86342940e-01  9.71583591e-02
  -1.05149957e-01  2.04457802e-01 -1.41230066e-01]
 [ 1.21154111e-01  1.79598553e-01 -2.84122317e-02 -2.22915429e-01
   1.05037284e-01 -1.50243792e-01 -1.81603010e-01]
 [ 1.40389484e-02  7.41104452e-02 -8.58758210e-02  5.00126637e-02
  -1.86464843e-01  2.44420705e-02  5.88852917e-02]
 [ 1.33308644e-01  2.95352401e-01 -2.63470895e-01  1.00521891e-01
   1.94900877e-02 -1.89351484e-01  1.02896702e-02]
 [-2.40932663e-01  1.85139086e-01  1.56195993e-01 -1.27708573e-01
   1.42531346e-01  2.32419390e-01  3.71005490e-02]
 [ 5.87590249e-02  4.82290743e-03 -3.63543958e-02 -8.87343261e-02
   8.83794046e-02 -4.74667079e-02 -2.39990082e-01]
 [ 1.23200375e-01  1.03326520e-01  1.99603065e-01  1.33157256e-01
  -2.00034189e-01 -1.13169448e-01  2.03834536e-01]
 [-1.33760496e-01  1.73257189e-02  1.37206204e-01 -6.08333405e-02
  -6.15449116e-02  1.92150311e-01  2.12108007e-03]
 [-9.48348831e-02  9.21623264e-02 -2.13629142e-01 -5.97994553e-02
  -1.82772621e-01 -4.53499672e-02 -2.09528701e-01]
 [ 2.81573017e-02  1.49561213e-01  1.35062767e-01  6.52346441e-02
   6.04614007e-03 -5.85855361e-02  2.40810453e-01]
 [ 2.12749753e-01 -2.67357872e-02 -2.03600292e-02 -1.10545311e-01
   1.25478940e-01  5.08029989e-03 -1.74751609e-01]
 [ 1.71163528e-01  6.73537336e-02 -1.06054659e-01 -2.30931446e-01
  -1.94792486e-01  8.09899669e-02 -7.94107059e-02]
 [ 2.15647955e-01  1.73109638e-01 -2.29475555e-01 -1.20830494e-01
   5.45070028e-02 -8.61451016e-02  3.10494635e-02]
 [-3.83235366e-02  6.76565259e-03  7.31525876e-02 -5.09641501e-02
   7.20294475e-02  8.24580690e-02  2.09013612e-01]
 [-1.93360815e-01 -2.23900493e-02  8.46179856e-02  2.03796024e-01
  -2.36428739e-01 -3.36460724e-01  4.39312780e-01]
 [-5.29912640e-02 -3.83566038e-02 -1.51527658e-02  1.41863974e-01
   1.29907701e-01 -8.79762567e-02  3.81942881e-01]
 [-1.85232107e-01 -1.37955459e-01  2.16677719e-01 -2.30759677e-01
  -1.55400757e-01 -1.82966928e-01 -2.80474150e-01]
 [-6.89532938e-02 -2.58339655e-01 -1.96633756e-01  2.41237948e-02
  -2.25787754e-01 -7.50832637e-02  3.74165428e-03]
 [-2.12141554e-01 -2.72141272e-01 -4.28974981e-02 -2.36726977e-01
   1.78838690e-01  1.92986975e-01 -5.86713899e-01]
 [-1.53608759e-01 -1.31487161e-01  8.85385421e-02  1.83990484e-02
  -7.93100375e-02 -2.08707439e-01 -9.06142243e-02]
 [-2.39354948e-02 -2.88520980e-01  1.26060924e-01 -1.61511708e-01
   4.46759249e-02  1.72250810e-01  1.77198747e-01]
 [ 1.02463426e-01  1.60600046e-01  8.07403012e-02 -2.22335848e-01
  -2.65761300e-02 -2.57451190e-02 -3.90890476e-02]
 [-2.30248177e-01  1.41990292e-01  6.73440399e-02 -9.67042013e-02
  -2.21717666e-01 -4.73373023e-02  1.84071954e-01]
 [-1.61167500e-01  1.84321504e-01 -1.31417412e-01  7.98540845e-02
  -1.02973294e-01 -8.05142119e-03  3.13814687e-01]
 [-1.34709644e-01  4.49285904e-01 -7.18809516e-02 -5.38180219e-02
   3.20876527e-02 -8.69119074e-02  4.15891099e-01]
 [ 8.93687119e-02 -1.58884455e-01 -2.12733381e-01 -2.18366292e-01
  -1.87674679e-01  1.03791935e-01 -1.60391034e-01]
 [ 1.39579244e-01  2.27215693e-01 -1.15898132e-01 -8.71670801e-02
   1.25791308e-01 -2.08746107e-01 -2.24820086e-01]
 [ 5.02820400e-02  4.27884339e-02  4.42568094e-02  1.09890594e-01
  -1.10744246e-01  3.28947093e-01 -1.30341573e-02]
 [-2.60572249e-01 -5.06134900e-02 -2.77472162e-01 -2.53299532e-01
  -6.71676777e-03  2.57496072e-01 -1.71489159e-01]
 [-1.54830255e-01 -1.58785549e-01 -1.11876262e-01  3.45189166e-02
  -1.46628248e-01 -3.57994021e-02 -1.65143049e-02]
 [ 6.98710508e-02  1.67011780e-01 -3.90358524e-02 -2.28200407e-01
  -3.48483769e-02 -1.88980654e-01  7.98283370e-02]
 [ 2.07569170e-01 -2.56561521e-01 -2.12337099e-01 -1.84022958e-01
  -1.49532961e-01  7.06116168e-02 -1.56857185e-01]
 [-1.05198827e-01 -2.73874716e-01  6.31597965e-02 -8.82176330e-02
  -2.21812321e-01  2.84075423e-01 -9.83076518e-02]
 [ 1.39916668e-01 -2.79956183e-01 -2.51805814e-01  6.65213017e-02
   2.45404630e-01  3.43940219e-01 -6.74375552e-01]
 [-1.19029074e-01  4.49233615e-01  1.25509303e-01  4.31899320e-02
  -1.95105421e-01 -1.98265565e-01  3.24567196e-01]
 [ 2.40525480e-02  3.21576526e-01 -2.49294999e-01  1.72495927e-01
   1.59647205e-01 -7.43317820e-02  2.70940602e-02]
 [ 1.00343342e-01  3.49961923e-02 -2.59048889e-02 -8.33599449e-02
  -1.95441548e-01 -1.88737597e-01 -3.97045458e-02]
 [-8.15961488e-02 -2.44687506e-01 -1.09266073e-01 -9.70781576e-02
  -2.31247362e-01 -5.69322034e-02 -1.93223330e-01]
 [-7.12790655e-02 -2.56231753e-01  1.02150193e-01  1.55249446e-01
  -1.18401525e-01 -5.12139891e-02  2.00333090e-01]
 [-3.21290347e-02  1.82664283e-01  1.44469115e-01 -1.93527502e-01
  -1.74490180e-01 -1.54400843e-01 -2.11310917e-01]]
第3层网络层:
权重矩阵维度: (7, 1)
系数矩阵：
 [[-0.77326283]
 [-0.46826283]
 [ 0.51280978]
 [ 0.01657018]
 [ 0.2356874 ]
 [ 0.68300453]
 [-1.28483001]]

In [209]:
# predict top 10 rate SA2:

In [210]:
y_pred_mlp = clf.predict(df_ceshi_scaled)

In [211]:
y_scaler.inverse_transform(y_pred_mlp.reshape((-1, 1)))

array([[ 0.13532672],
       [ 0.24727679],
       [ 0.3077363 ],
       [ 0.18103812],
       [ 0.30546762],
       [ 0.14878789],
       [ 0.2579098 ],
       [ 0.17141809],
       [ 0.13772881],
       [ 0.14097116],
       [ 0.34671403],
       [ 0.30725589],
       [ 0.2481585 ],
       [ 0.35954366],
       [ 0.27438942],
       [ 0.29072158],
       [ 0.34955583],
       [ 0.23117392],
       [ 0.26207953],
       [ 0.14054622],
       [ 0.1608923 ],
       [ 0.19316137],
       [ 0.20370149],
       [ 0.20691622],
       [ 0.15458383],
       [ 0.13285746],
       [ 0.11547359],
       [ 0.22594463],
       [ 0.26089871],
       [ 0.29236798],
       [ 0.27592591],
       [ 0.31551637],
       [ 0.23510385],
       [ 0.35560442],
       [ 0.26535829],
       [ 0.06920209],
       [ 0.19466636],
       [ 0.25303503],
       [ 0.13308572],
       [ 0.14720418],
       [ 0.12041518],
       [ 0.12740968],
       [ 0.15556947],
       [ 0.16524328],
       [ 0.15922549],
       [ 0.11873267],
       [ 0.17387708],
       [ 0.04793073],
       [ 0.17235856],
       [ 0.15624999],
       [ 0.15031987],
       [ 0.20174166],
       [ 0.32581402],
       [ 0.33688982],
       [ 0.32100087],
       [ 0.13933966],
       [ 0.07386755],
       [ 0.20987144],
       [ 0.27953545],
       [ 0.27723004],
       [ 0.14953209],
       [ 0.35354742],
       [ 0.26833308],
       [ 0.28182352],
       [ 0.18842761],
       [ 0.25789208],
       [ 0.29466426],
       [ 0.29894926],
       [ 0.27916674],
       [ 0.21265976],
       [ 0.36761074],
       [ 0.26698172],
       [ 0.31096289],
       [ 0.27434114],
       [ 0.27939886],
       [ 0.31122982],
       [ 0.14627425],
       [ 0.25637105],
       [ 0.05314406],
       [ 0.16186608],
       [ 0.19370848],
       [ 0.29634964],
       [ 0.24031819],
       [ 0.20468833],
       [ 0.18891062],
       [ 0.31825666],
       [ 0.28198145],
       [ 0.24588784],
       [ 0.30094767],
       [ 0.30967541],
       [ 0.2901919 ],
       [ 0.27884624],
       [ 0.29779863],
       [ 0.29125426],
       [ 0.13068533],
       [ 0.19506457],
       [ 0.16739235],
       [ 0.21928601],
       [ 0.13191569],
       [ 0.15299045],
       [ 0.27081294],
       [ 0.16696731],
       [ 0.19773302],
       [ 0.1627201 ],
       [ 0.28499251],
       [ 0.0094015 ],
       [ 0.09555484],
       [ 0.12912171],
       [ 0.0537285 ],
       [ 0.02512828],
       [ 0.12963577],
       [ 0.13102768],
       [ 0.09256082],
       [ 0.10579931],
       [ 0.07714325],
       [ 0.05889901],
       [ 0.08368354],
       [ 0.06523385],
       [ 0.09700572],
       [ 0.15163448],
       [ 0.10359106],
       [ 0.00866405],
       [-0.03957449],
       [ 0.01910183],
       [ 0.03917363],
       [ 0.0266201 ],
       [ 0.03908907],
       [ 0.01132372],
       [-0.0077055 ],
       [-0.00845561],
       [ 0.03729805],
       [ 0.02611603],
       [-0.00406421],
       [ 0.02300323],
       [ 0.0524989 ],
       [ 0.04119128],
       [ 0.07767544],
       [ 0.02518421],
       [ 0.00154868],
       [ 0.05297384],
       [ 0.02508833],
       [ 0.04898475],
       [ 0.06985243],
       [-0.00293433],
       [ 0.15577692],
       [-0.07053175],
       [ 0.0161244 ],
       [-0.01803738],
       [ 0.03166933],
       [-0.02910032],
       [ 0.01531569],
       [ 0.03297015],
       [ 0.04787312],
       [-0.06639724],
       [ 0.01503101],
       [ 0.08240632],
       [ 0.19404109],
       [ 0.12760284],
       [ 0.14547934],
       [ 0.12523866],
       [ 0.03331387],
       [ 0.05609443],
       [ 0.19146851],
       [ 0.04414796],
       [ 0.01667535],
       [ 0.15153537],
       [ 0.14284775],
       [ 0.15878588],
       [ 0.13523168],
       [ 0.17915857],
       [ 0.15802354],
       [ 0.13176278],
       [ 0.11009656],
       [ 0.11350436],
       [ 0.15628243],
       [ 0.08999633],
       [ 0.11715707],
       [ 0.09557024],
       [ 0.10648388],
       [ 0.14723832],
       [ 0.24815345],
       [ 0.16030681],
       [ 0.18774999],
       [ 0.16453063],
       [ 0.16030814],
       [ 0.22305536],
       [ 0.09600873],
       [ 0.10972446],
       [ 0.07258001],
       [ 0.14876178],
       [ 0.09941103],
       [ 0.10883177],
       [ 0.11694873],
       [ 0.09515054],
       [ 0.14974836],
       [ 0.17963114],
       [ 0.15098116],
       [ 0.170577  ],
       [ 0.16127841],
       [ 0.14650878],
       [ 0.10731094],
       [ 0.1851142 ],
       [ 0.19699938],
       [ 0.15501083],
       [ 0.13980455],
       [ 0.08701354],
       [ 0.09003399],
       [ 0.10533558],
       [ 0.13117382],
       [ 0.16076159],
       [ 0.14274684],
       [ 0.16521202],
       [ 0.12526429],
       [ 0.1709744 ],
       [ 0.12576427],
       [ 0.14104215],
       [ 0.12696056],
       [ 0.1033366 ],
       [ 0.1667423 ],
       [ 0.14965902],
       [ 0.10923677],
       [ 0.14389491],
       [ 0.15750085],
       [ 0.11792374],
       [ 0.13880269],
       [ 0.20492033],
       [ 0.22913483],
       [ 0.16001787],
       [ 0.08741833],
       [ 0.17017248],
       [ 0.11136168],
       [ 0.13997745],
       [ 0.12746192],
       [ 0.09735661],
       [ 0.20990386],
       [ 0.08434496],
       [ 0.08379141],
       [ 0.09349638],
       [ 0.09315337],
       [ 0.08239042],
       [ 0.08606013],
       [ 0.10963585],
       [ 0.08796094],
       [ 0.08355544],
       [ 0.0496146 ],
       [ 0.07429847],
       [ 0.07735964],
       [ 0.08648332],
       [ 0.05546335],
       [ 0.15588796],
       [ 0.16821942],
       [ 0.13352364],
       [ 0.16140235],
       [ 0.15681005],
       [ 0.15873079],
       [ 0.16896409],
       [ 0.12975042],
       [ 0.15259373],
       [ 0.13480314],
       [ 0.150451  ],
       [ 0.12486605],
       [ 0.08635181],
       [ 0.12010266],
       [ 0.14617834],
       [ 0.14263189],
       [ 0.10541027],
       [ 0.13268863],
       [ 0.12735027],
       [ 0.06070301],
       [ 0.1228768 ],
       [ 0.10799575],
       [ 0.11929819],
       [ 0.13843619],
       [ 0.14028019],
       [ 0.05644999],
       [ 0.09928406],
       [ 0.1220801 ],
       [ 0.07868123],
       [ 0.09023298],
       [ 0.0812818 ],
       [ 0.05311929],
       [ 0.04772502],
       [ 0.08367081],
       [ 0.07453174],
       [ 0.05433294],
       [ 0.13960524],
       [ 0.14144455],
       [ 0.08897088],
       [ 0.15388141],
       [ 0.1515484 ],
       [ 0.16064961],
       [ 0.13808996],
       [ 0.15371643],
       [ 0.12522716],
       [ 0.1460787 ],
       [ 0.14027717],
       [ 0.10223759],
       [ 0.22739911],
       [ 0.19367893],
       [ 0.14716691],
       [ 0.1570896 ],
       [ 0.1426802 ],
       [ 0.12681599],
       [ 0.18938232],
       [ 0.1638515 ],
       [ 0.15864434],
       [ 0.1184458 ],
       [ 0.16087416],
       [ 0.15531745],
       [ 0.18176826],
       [ 0.16476463],
       [ 0.17797548],
       [ 0.1548099 ],
       [ 0.1355161 ],
       [ 0.14884283],
       [ 0.13278977],
       [ 0.14665969],
       [ 0.13987655],
       [ 0.1347042 ],
       [ 0.10414576],
       [ 0.20848037],
       [ 0.13092546],
       [ 0.16937022],
       [ 0.12278995],
       [ 0.14459941],
       [ 0.14487268],
       [ 0.07295552],
       [ 0.14084816],
       [ 0.1094108 ],
       [ 0.12428075],
       [ 0.07280519],
       [ 0.16661662],
       [ 0.08515122],
       [ 0.14158058],
       [ 0.13276676],
       [ 0.1099245 ],
       [ 0.13914483],
       [ 0.13328467],
       [ 0.125313  ],
       [ 0.12964913],
       [ 0.13483295],
       [ 0.10630169],
       [ 0.11074044],
       [ 0.13277765],
       [ 0.0863782 ],
       [ 0.09739298],
       [ 0.08623406],
       [ 0.13116337],
       [ 0.1004629 ],
       [ 0.109976  ],
       [ 0.05851549],
       [ 0.05609025],
       [ 0.07911438],
       [ 0.08083584],
       [ 0.06820259],
       [ 0.10771973],
       [ 0.11285113],
       [ 0.12097155],
       [ 0.16227258],
       [ 0.15660027],
       [ 0.13627367],
       [ 0.19244662],
       [ 0.12966178],
       [ 0.13056881],
       [ 0.12448218],
       [ 0.16639354],
       [ 0.14794404],
       [ 0.12466996],
       [ 0.16508012],
       [ 0.13328826],
       [ 0.11356502],
       [ 0.12834255],
       [ 0.1328968 ],
       [ 0.13152645],
       [ 0.17166412],
       [ 0.13843439],
       [ 0.14406897],
       [ 0.10973967],
       [ 0.18345407],
       [ 0.26012693],
       [ 0.14909605],
       [ 0.23796761],
       [ 0.1038104 ],
       [ 0.14455186],
       [ 0.14680801],
       [ 0.13753436],
       [ 0.1655075 ],
       [ 0.17620989],
       [ 0.19174607],
       [ 0.1346635 ],
       [ 0.16862683],
       [ 0.15595886],
       [ 0.19798124],
       [ 0.15862205],
       [ 0.07670656],
       [ 0.21511551],
       [ 0.1751876 ],
       [ 0.17631076],
       [ 0.10162333],
       [ 0.19185366],
       [ 0.19817871],
       [ 0.13220434],
       [ 0.1446795 ],
       [ 0.17058223],
       [ 0.15702689],
       [ 0.15879742],
       [ 0.07762755],
       [ 0.10891382],
       [ 0.12300158],
       [ 0.08198462],
       [ 0.08936357],
       [ 0.14165583],
       [ 0.11728767],
       [ 0.11363646],
       [ 0.08729855],
       [ 0.04919102],
       [ 0.10148787],
       [ 0.07612   ],
       [ 0.14343594],
       [ 0.10785063],
       [ 0.11125241],
       [ 0.13680687],
       [ 0.15326052],
       [ 0.16096725],
       [ 0.14677961],
       [ 0.16346997],
       [ 0.06989145],
       [ 0.07221445],
       [ 0.16354955],
       [ 0.09153314],
       [ 0.07641137],
       [ 0.16345012],
       [ 0.10601616],
       [ 0.03715518],
       [ 0.03250984],
       [ 0.0468208 ],
       [ 0.10310134],
       [ 0.03787451],
       [ 0.08611353],
       [ 0.09210162],
       [ 0.07697009],
       [ 0.12357549],
       [ 0.14632141],
       [ 0.15826308],
       [ 0.18646885],
       [ 0.18361893],
       [ 0.11664033],
       [ 0.18859702],
       [ 0.17202915],
       [ 0.18364495],
       [ 0.3513272 ],
       [ 0.1648368 ],
       [ 0.20423403],
       [ 0.18298529],
       [ 0.21883073],
       [ 0.21856981],
       [ 0.17878233],
       [ 0.1834799 ],
       [ 0.27362814],
       [ 0.19454269],
       [ 0.38649291],
       [ 0.20300896],
       [ 0.35662715],
       [ 0.23241072],
       [ 0.30395468],
       [ 0.21050325],
       [ 0.400853  ],
       [ 0.2236743 ],
       [ 0.19502772],
       [ 0.31154342],
       [ 0.40084706],
       [ 0.28000264],
       [ 0.19634309],
       [ 0.19890292],
       [ 0.22768221],
       [ 0.25754732],
       [ 0.29432419],
       [ 0.4607192 ],
       [ 0.16250451],
       [ 0.25424299],
       [ 0.20889018],
       [ 0.18709982],
       [ 0.36399648],
       [ 0.35162212],
       [ 0.26989028],
       [ 0.24638849],
       [ 0.46860789],
       [ 0.18167641],
       [ 0.25020044],
       [ 0.22161352],
       [ 0.18342299],
       [ 0.34061904],
       [ 0.2132346 ],
       [ 0.16569824],
       [ 0.18037643],
       [ 0.26738963],
       [ 0.20774802],
       [ 0.21148005],
       [ 0.3363424 ],
       [ 0.38574222],
       [ 0.1929997 ],
       [ 0.37231549],
       [ 0.32877279],
       [ 0.32066797],
       [ 0.32728401],
       [ 0.33024665],
       [ 0.25754549],
       [ 0.19488959],
       [ 0.23333747]])

In [212]:
y_pred_lr = lr.predict(df_ceshi_scaled)

In [213]:
df_pred = pd.DataFrame()
df_pred['SA2_CODE21'] = df_ceshi['SA2_CODE16']
df_pred['ror_mlp_pred'] = y_scaler.inverse_transform(y_pred_mlp.reshape((-1, 1)))
df_pred['ror_lr_pred'] = y_scaler.inverse_transform(y_pred_lr.reshape((-1, 1)))

In [214]:
df_pred.sort_values(["ror_mlp_pred"] , ascending=False) [:10]

     SA2_CODE21  ror_mlp_pred  ror_lr_pred
499   216021412      0.468608     0.291951
490   215031403      0.460719     0.197406
479   215011393      0.400853     0.320143
483   215021398      0.400847     0.275606
473   215011387      0.386493     0.295874
512   217031471      0.385742     0.311038
514   217031473      0.372315     0.256899
71    204021067      0.367611     0.247050
495   216011408      0.363996     0.264576
13    201021012      0.359544     0.215883

In [215]:
df_pred.sort_values(["ror_lr_pred"] , ascending=False)[:10]

     SA2_CODE21  ror_mlp_pred  ror_lr_pred
91    205021086      0.300948     0.367584
54    203031052      0.321001     0.341322
53    203031051      0.336890     0.339677
90    205021085      0.245888     0.330823
477   215011391      0.303955     0.327841
14    201031013      0.274389     0.325913
489   215031402      0.294324     0.325321
497   216011410      0.269890     0.324798
110   205051104      0.284993     0.320194
479   215011393      0.400853     0.320143

In [216]:
print("Top 10 growth rate SA2_CODE(MLP predict) are ",df_pred.sort_values(["ror_mlp_pred"] , ascending=False)[:10].SA2_CODE21.values)

Top 10 growth rate SA2_CODE(MLP predict) are  [216021412 215031403 215011393 215021398 215011387 217031471 217031473
 204021067 216011408 201021012]

In [217]:
print("Top 10 growth rate SA2_CODE(LR predict) are ",df_pred.sort_values(["ror_lr_pred"] , ascending=False)[:10].SA2_CODE21.values)

Top 10 growth rate SA2_CODE(LR predict) are  [205021086 203031052 203031051 205021085 215011391 201031013 215031402
 216011410 205051104 215011393]